### ISSUE TITLE
Adding __hash__ operator to support set operation for RegexPattern

### ISSUE THREAD

**Issue by jeffrey82221** [GrandMoff100/RegexFactory#12]
Hi @GrandMoff100 , 

I wonder if you can add __hash__ operator to support set operation for RegexPattern. 

The use case is as follows:

```python
from regexfactory.chars import ANY, DIGIT
from regexfactory.pattern import escape
set([ANY, ANY, DIGIT, DIGIT, escape('apple'), escape('apple')]) 
>> {<RegexPattern '.'>, <RegexPattern '\d'>, <RegexPattern 'apple'>}
```
Without __hash__, the above situation will raise: 

`TypeError: unhashable type: 'RegexPattern'`.

A simple additional `__hash__` method to the RegexPattern class may solve the problem:

```python
    def __hash__(self):
         return hash(self.regex)
```

I am willing to make this contribute, too. Is it possible to add this new feature to the near future release (maybe v1.0.1)?

**Comment by GrandMoff100** [comment]
I love this idea. You bring up a valid point. We can definitely include it in new release. Would you like to ship it with the rest of your contributions and would you rather we release in a separate minor release before the rest of your contributions?
